name: Gerar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Extrair projeto
        run: |
          unzip -o CHRIS_CELL_ANDROID.zip
          cp gradle.properties CHRIS_CELL_ANDROID/gradle.properties
          cd CHRIS_CELL_ANDROID

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.11.1-bin.zip
          unzip -q gradle-8.11.1-bin.zip
          echo "$PWD/gradle-8.11.1/bin" >> $GITHUB_PATH

      - name: Compilar APK
        run: |
          cd CHRIS_CELL_ANDROID
          gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Chris-Cell-APK
          path: CHRIS_CELL_ANDROID/app/build/outputs/apk/debug/app-debug.apk
